### ISSUE TITLE
Expected performance

### ISSUE THREAD

**Issue by s1ddok** [EndlessSora/focal-frequency-loss#1]
Hello!

Thanks for this awesome work! I can't wait to try your SPADE experiments myself. I wonder did you use vanilla PyTorch to implement this loss or you used any specific library? Does it have significant impact on training performance?

**Comment by EndlessSora** [comment]
Hi @s1ddok, thanks a lot for your interest in our work! We will release our code and all the experiment implementations very soon when the time is suitable. ;-)
Thanks for your patience and understanding!~

**Comment by EndlessSora** [comment]
The code is now released. Thanks. :-)
