### ISSUE TITLE
a question about ffl value

### ISSUE THREAD

**Issue by balabala932131** [EndlessSora/focal-frequency-loss#13]
Thanks for your good job!
recently i am apply it for my  work, i find its well for Image Reconstruction. but i am confuse for how big its value ? Generally speaking，for gan, we will have two loss. can you provide some experience for two loss? should i initialize two loss is equal?

**Comment by EndlessSora** [comment]
The value of FFL should have been normalized, so it should be in a reasonable range. And yes, initializing two losses as equal/at the same order of magnitude is a good starting point. You can adjust their weights after that.
