### ISSUE TITLE
 the spectra of images

### ISSUE THREAD

**Issue by jiandandan001** [EndlessSora/focal-frequency-loss#6]
Great work! Thank you for sharing the code. 

Could you please share the code to draw the  spectra of images?  Thanks.

**Comment by EndlessSora** [comment]
Thank you for your interest. You may try the following Python code to visualize the spectrum:

```python
import matplotlib.pyplot as plt
import numpy as np

# `img` is a single-channel grey-scale image (numpy.ndarray or PIL.Image) that is converted from RGB or BGR
freq = np.fft.fft2(img)
freq = np.fft.fftshift(freq)
freq = np.log(1 + np.abs(freq))
plt.imsave('freq.png', freq)
```

**Comment by jiandandan001** [comment]
> Thank you for your interest. You may try the following Python code to visualize the spectrum:
> 
> ```python
> import matplotlib.pyplot as plt
> import numpy as np
> 
> # `img` is a single-channel grey-scale image (numpy.ndarray or PIL.Image) that is converted from RGB or BGR
> freq = np.fft.fft2(img)
> freq = np.fft.fftshift(freq)
> freq = np.log(1 + np.abs(freq))
> plt.imsave('freq.png', freq)
> ```

Thanks!
