### ISSUE TITLE
About the calculation of distance

### ISSUE THREAD

**Issue by IItaly** [EndlessSora/focal-frequency-loss#9]
https://github.com/EndlessSora/focal-frequency-loss/blob/5c34c2cb03bb9b26fa917fd9f032c009599290a5/focal_frequency_loss/focal_frequency_loss.py#L90
Thanks for your work
I want to know the calculation of the distance.
Euclidean distance needs square operation and why here just "tmp[...,0],tmp[...,1]"
what does it mean?

**Comment by EndlessSora** [comment]
> https://github.com/EndlessSora/focal-frequency-loss/blob/5c34c2cb03bb9b26fa917fd9f032c009599290a5/focal_frequency_loss/focal_frequency_loss.py#L89
Thanks for your interest. We performed the square operation in Line 89. We use the squared Euclidean distance. You can consider printing each tensor out to understand the code.

**Comment by EndlessSora** [comment]
No. You can regard the square root of `freq_distance` in Line 90 as the Euclidean distance. We apply the squared Euclidean distance to ensure a smooth gradient.

**Comment by EndlessSora** [comment]
Please note that since FFLoss keeps decreasing during training, your mentioned 1/FFLoss would increase as FFLoss decreases. If you would like the frequency distance to be larger as the model is trained, you may apply -FFLoss as your objective function.
